//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Year { get; set; }
        public System.DateTime EndYear { get; set; }
        public double Price { get; set; }
    
        public virtual Model Model { get; set; }
    }
}
